  - name: Copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb 
    ansible.builtin.include_role:
      name: common
      tasks_from: install_package

  - name: start and enable mongod
    ansible.builtin.include_role:
      name: common
      tasks_from: start_enable_service
    

  - name: mongodb port open
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    notify: Restart mongod
    