[local]
localhost


[mongodb]
mongodb.yaswanthreddypenchikala.online

[redis]
redis.yaswanthreddypenchikala.online

[frontend]
nginx.yaswanthreddypenchikala.online

[catalogue]
catalogue.yaswanthreddypenchikala.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321